name: Release tests

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
      - uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITOPS_GH_TOKEN }}
          with-v: "true"
          bump: patch
