name: Glob tests

on:
  push:
    branches:
      - "*"
      - "!v[0-9]*.*"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
