name: Version tests

on:
  push:
    branches:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        
